<a href="https://colab.research.google.com/github/abubakar1109/Full-Stack-Data-Scientist-BootCamp/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
a=pd.Series([10,20,30,40,50])
print(a)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
b=pd.Series([1,2,3,4,5,6], index=['a','b','c','d','e','f'])
print(b)

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [6]:
c=pd.DataFrame({
    'Name': ['Ahmad','Basil','Taha','Mughal'],
    'Age':[22,22,23,23],
    'Martial_Status':['Single','Single','Single','Single']})
print(c)

     Name  Age Martial_Status
0   Ahmad   22         Single
1   Basil   22         Single
2    Taha   23         Single
3  Mughal   23         Single

In [8]:
print(c.head(2))

    Name  Age Martial_Status
0  Ahmad   22         Single
1  Basil   22         Single

In [9]:
print(c.tail(2))

     Name  Age Martial_Status
2    Taha   23         Single
3  Mughal   23         Single

In [10]:
print(c.info())
print(c.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Martial_Status  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes
None
            Age
count   4.00000
mean   22.50000
std     0.57735
min    22.00000
25%    22.00000
50%    22.50000
75%    23.00000
max    23.00000

In [13]:
print("Name Registered\n",c['Name'])
print("Age Registered\n",c['Age'])

Name Registered
 0     Ahmad
1     Basil
2      Taha
3    Mughal
Name: Name, dtype: object
Age Registered
 0    22
1    22
2    23
3    23
Name: Age, dtype: int64

In [18]:
print(c.loc[1,'Age'])

22

In [19]:
print(c.iloc[0,1])

22

In [20]:
print(c.loc[0:2,'Name'])

0    Ahmad
1    Basil
2     Taha
Name: Name, dtype: object

In [21]:
print("Students Having Age = 22 ",c[c['Age'] == 22])

Students Having Age = 22      Name  Age Martial_Status
0  Ahmad   22         Single
1  Basil   22         Single

In [22]:
c.isnull()

    Name    Age  Martial_Status
0  False  False           False
1  False  False           False
2  False  False           False
3  False  False           False

In [23]:
c.isnull().sum()

Name              0
Age               0
Martial_Status    0
dtype: int64

In [24]:
c.drop('Martial_Status',axis=1)

     Name  Age
0   Ahmad   22
1   Basil   22
2    Taha   23
3  Mughal   23

In [29]:
c['Salary']=c['Age']*1200
print(c)

     Name  Age Martial_Status  Salary
0   Ahmad   22         Single   26400
1   Basil   22         Single   26400
2    Taha   23         Single   27600
3  Mughal   23         Single   27600

In [31]:
c.drop("Martial_Status",axis=1,inplace=True)

In [32]:
c

     Name  Age  Salary
0   Ahmad   22   26400
1   Basil   22   26400
2    Taha   23   27600
3  Mughal   23   27600

In [33]:
c['Reg_No']=[7,99,33,29]

In [34]:
c.set_index('Reg_No',inplace=True)

In [35]:
c

          Name  Age  Salary
Reg_No
7        Ahmad   22   26400
99       Basil   22   26400
33        Taha   23   27600
29      Mughal   23   27600

In [36]:
data=pd.read_csv('/content/sample_data/mnist_test.csv')

In [37]:
data.head()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [38]:
data.columns

Index(['7', '0', '0.1', '0.2', '0.3', '0.4', '0.5', '0.6', '0.7', '0.8',
       ...
       '0.658', '0.659', '0.660', '0.661', '0.662', '0.663', '0.664', '0.665',
       '0.666', '0.667'],
      dtype='object', length=785)

In [39]:
data.isnull().sum()

7        0
0        0
0.1      0
0.2      0
0.3      0
        ..
0.663    0
0.664    0
0.665    0
0.666    0
0.667    0
Length: 785, dtype: int64

In [40]:
data.describe()

,7,0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,0.658,0.659,0.660,0.661,0.662,0.663,0.664,0.665,0.666,0.667
count,9999.000000,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0,...,9999.000000,9999.000000,9999.000000,9999.000000,9999.0,9999.0,9999.0,9999.0,9999.0,9999.0
mean,4.443144,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.179318,0.163616,0.052605,0.000600,0.0,0.0,0.0,0.0,0.0,0.0
std,2.895897,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,5.674433,5.736359,2.420125,0.060003,0.0,0.0,0.0,0.0,0.0,0.0
min,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
25%,2.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
50%,4.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
75%,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
max,9.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,253.000000,253.000000,156.000000,6.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
data.describe().T

        count      mean       std  min  25%  50%  75%  max
7      9999.0  4.443144  2.895897  0.0  2.0  4.0  7.0  9.0
0      9999.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
0.1    9999.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
0.2    9999.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
0.3    9999.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
...       ...       ...       ...  ...  ...  ...  ...  ...
0.663  9999.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
0.664  9999.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
0.665  9999.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
0.666  9999.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0
0.667  9999.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0

[785 rows x 8 columns]

In [46]:
data1=pd.read_csv('/content/sample_data/california_housing_test.csv')

In [47]:
data1.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [49]:
data1[(data1['total_rooms']<100) & (data1['population']<100) ]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
564,-121.98,37.14,37.0,74.0,19.0,63.0,17.0,9.5908,350000.0
666,-121.89,37.42,26.0,40.0,8.0,52.0,7.0,7.7197,225000.0
733,-117.99,33.81,46.0,38.0,8.0,66.0,14.0,4.1667,162500.0
740,-117.12,32.66,52.0,16.0,4.0,8.0,3.0,1.1250,60000.0
742,-122.22,37.88,20.0,95.0,13.0,31.0,15.0,2.4444,475000.0
826,-118.25,34.06,20.0,41.0,17.0,87.0,25.0,1.5491,225000.0
842,-117.95,35.08,1.0,83.0,15.0,32.0,15.0,4.8750,141700.0
1115,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.6250,55000.0
1202,-117.30,34.10,49.0,60.0,11.0,76.0,13.0,2.5625,75000.0
1345,-121.29,37.33,36.0,48.0,12.0,27.0,8.0,4.0000,75000.0
1355,-117.11,32.66,52.0,25.0,5.0,14.0,9.0,1.6250,118800.0
1356,-121.90,37.39,42.0,42.0,14.0,26.0,14.0,1.7361,500001.0
1509,-119.02,35.38,52.0,90.0,35.0,36.0,31.0,0.8054,60000.0
1539,-120.79,37.08,9.0,97.0,20.0,91.0,22.0,2.9063,55000.0
1726,-117.05,33.03,16.0,87.0,20.0,32.0,21.0,4.3571,144600.0
1902,-117.90,36.95,19.0,99.0,26.0,51.0,22.0,1.7292,137500.0
2132,-121.84,36.62,26.0,32.0,8.0,27.0,10.0,2.2250,150000.0
2494,-118.44,34.04,49.0,32.0,7.0,14.0,7.0,2.1875,225000.0
2502,-118.23,33.76,21.0,49.0,14.0,29.0,16.0,5.0000,87500.0
2636,-120.92,37.63,39.0,45.0,8.0,22.0,9.0,1.7679,450000.0
2640,-114.62,33.62,26.0,18.0,3.0,5.0,3.0,0.5360,275000.0
2690,-118.06,34.03,36.0,21.0,7.0,21.0,9.0,2.3750,175000.0
2768,-122.49,38.00,26.0,48.0,8.0,19.0,8.0,7.7197,400000.0
2879,-121.84,38.02,46.0,66.0,22.0,37.0,21.0,0.5360,87500.0
2998,-117.12,34.10,40.0,96.0,14.0,46.0,14.0,3.2708,162500.0

In [50]:
data1.groupby('population').count()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,households,median_income,median_house_value
population,,,,,,,,
5.0,1,1,1,1,1,1,1,1
8.0,2,2,2,2,2,2,2,2
14.0,2,2,2,2,2,2,2,2
19.0,1,1,1,1,1,1,1,1
21.0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...
8824.0,1,1,1,1,1,1,1,1
9419.0,1,1,1,1,1,1,1,1
10877.0,1,1,1,1,1,1,1,1
11139.0,1,1,1,1,1,1,1,1
11935.0,1,1,1,1,1,1,1,1

In [51]:
data1['median_income'].value_counts()

median_income
15.0001    9
4.0000     8
3.3750     8
3.2500     7
3.8750     7
          ..
3.2440     1
5.0659     1
5.2449     1
5.0406     1
1.9963     1
Name: count, Length: 2578, dtype: int64

In [52]:
ff= {
    'a':[1,2,3,4,5],
    'b':[6,7,8,9,10]
}

In [53]:
ff1=pd.DataFrame(ff)

In [54]:
ff1

   a   b
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [55]:
concat=pd.concat([ff1,c])

In [56]:
concat

      a     b    Name   Age   Salary
0   1.0   6.0     NaN   NaN      NaN
1   2.0   7.0     NaN   NaN      NaN
2   3.0   8.0     NaN   NaN      NaN
3   4.0   9.0     NaN   NaN      NaN
4   5.0  10.0     NaN   NaN      NaN
7   NaN   NaN   Ahmad  22.0  26400.0
99  NaN   NaN   Basil  22.0  26400.0
33  NaN   NaN    Taha  23.0  27600.0
29  NaN   NaN  Mughal  23.0  27600.0

In [62]:
sales = {'Ahmad': 10000,
         'Mughal': 5000,
         'Basil': 440,
         'Taha': 6700,
         'Quershi': 300
        }

region = {'Ahmad': 'West',
          'Mughal': np.nan,
          'Taha': 'West',
          'Abdur Rehman': np.nan,
          'Ayesha': 'East',
          'Araysh': 'South',
          'Saira': 'West',
        }

In [63]:
sales_df = pd.DataFrame.from_dict(sales, orient='index',
                                  columns=['sales'])
region_df = pd.DataFrame.from_dict(region, orient='index',
                                   columns=['region'])

In [64]:
sales_df

         sales
Ahmad    10000
Mughal    5000
Basil      440
Taha      6700
Quershi    300

In [65]:
region_df

             region
Ahmad          West
Mughal          NaN
Taha           West
Abdur Rehman    NaN
Ayesha         East
Araysh        South
Saira          West

In [66]:
Left_join_df = region_df.join(sales_df, how='left')
Right_join_df = region_df.join(sales_df, how='right')
inner_join_df = region_df.join(sales_df, how='inner')
outer_join_df = region_df.join(sales_df, how='outer')

In [70]:
print('Left Join\n',Left_join_df)
print('Right Join\n',Right_join_df)
print('Inner Join\n',inner_join_df)
print('Outer Join\n',outer_join_df)

Left Join
              region    sales
Ahmad          West  10000.0
Mughal          NaN   5000.0
Taha           West   6700.0
Abdur Rehman    NaN      NaN
Ayesha         East      NaN
Araysh        South      NaN
Saira          West      NaN
Right Join
         region  sales
Ahmad     West  10000
Mughal     NaN   5000
Basil      NaN    440
Taha      West   6700
Quershi    NaN    300
Inner Join
        region  sales
Ahmad    West  10000
Mughal    NaN   5000
Taha     West   6700
Outer Join
              region    sales
Abdur Rehman    NaN      NaN
Ahmad          West  10000.0
Araysh        South      NaN
Ayesha         East      NaN
Basil           NaN    440.0
Mughal          NaN   5000.0
Quershi         NaN    300.0
Saira          West      NaN
Taha           West   6700.0

In [73]:
region_df.index.name='names'
sales_df.index.name='names'

In [74]:
print(pd.merge(region_df,sales_df,on='names',how='right'))

        region  sales
names
Ahmad     West  10000
Mughal     NaN   5000
Basil      NaN    440
Taha      West   6700
Quershi    NaN    300

In [75]:
print(pd.merge(region_df,sales_df,on='names',how='left'))

             region    sales
names
Ahmad          West  10000.0
Mughal          NaN   5000.0
Taha           West   6700.0
Abdur Rehman    NaN      NaN
Ayesha         East      NaN
Araysh        South      NaN
Saira          West      NaN