<a href="https://colab.research.google.com/github/abubakar1109/Full-Stack-Data-Scientist-BootCamp/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing Library

In [2]:
import numpy as np

List to Array

In [3]:
myList=[1,2,3,4,5]
n=np.array(myList)
n

array([1, 2, 3, 4, 5])

In [4]:
type(myList)

list

In [5]:
type(n)

numpy.ndarray

Creating a Multi Dimensional Array

In [8]:
list_of_list=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
list_of_list

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
list_of_list.shape

(3, 3)

Arange Function

In [15]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [16]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [18]:
for i in range(0,10):
  print(i)

0
1
2
3
4
5
6
7
8
9

In [19]:
np.arange(0,20,4)

array([ 0,  4,  8, 12, 16])

Zeros Function

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Ones Function

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Eye Function

In [25]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Reshape function

In [26]:
m=np.arange(0,10)

In [28]:
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
len(m)

10

In [31]:
m.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Linspace Function

In [33]:
x=np.linspace(0,5,5)

In [34]:
x

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

In [35]:
len(x)

5

Resize Function

In [36]:
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
m.resize(2,5)

In [41]:
m

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

Generate Some Random Value

In [42]:
np.random.rand(3,2)

array([[0.69262266, 0.31079945],
       [0.64094903, 0.32222717],
       [0.48343899, 0.52857607]])

In [45]:
np.random.randn(3,2)

array([[ 1.88381224,  0.39629922],
       [ 1.0749936 , -0.11237466],
       [-0.81647574, -0.94951376]])

In [47]:
y=np.random.randint(0,10,10)

In [48]:
y

array([5, 2, 0, 7, 0, 2, 6, 7, 7, 8])

In [49]:
y.reshape(2,5)

array([[5, 2, 0, 7, 0],
       [2, 6, 7, 7, 8]])

In [50]:
np.random.randint(0,10,(3,3))

array([[6, 6, 3],
       [1, 6, 6],
       [8, 8, 8]])

Indexing & Slicing

In [51]:
z=np.random.randint(4,15,10)

In [52]:
z

array([12,  9, 13,  7, 10, 14,  7, 10, 12,  9])

In [53]:
z[1]

np.int64(9)

In [54]:
z[-1]

np.int64(9)

In [55]:
z[3:7]

array([ 7, 10, 14,  7])

In [56]:
a=np.arange(64)

In [57]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [58]:
a.resize(8,8)

In [59]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [60]:
a[0,0]

np.int64(0)

In [61]:
a[1,1]

np.int64(9)

In [62]:
a[2,2]

np.int64(18)

In [64]:
a[7,7]

np.int64(63)

In [65]:
a[4,2:5]

array([34, 35, 36])

In [66]:
a[2:]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [67]:
a[2:,2:]

array([[18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55],
       [58, 59, 60, 61, 62, 63]])

In [68]:
a[:,2]

array([ 2, 10, 18, 26, 34, 42, 50, 58])

In [71]:
a>32

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [70]:
a[a>32]

array([33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49,
       50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [72]:
a[a>32]=32

In [73]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 32, 32, 32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32, 32, 32, 32]])

Creating a Copy

In [74]:
a=a[3:,3:]

In [75]:
a

array([[27, 28, 29, 30, 31],
       [32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32]])

In [76]:
a_copy=a.copy()

In [77]:
a_copy

array([[27, 28, 29, 30, 31],
       [32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32],
       [32, 32, 32, 32, 32]])

DataFrame

In [80]:
import pandas as pd
data=pd.read_csv("/content/sample_data/california_housing_test.csv")

In [81]:
data.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [84]:
df=data.copy()

In [85]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [86]:
df["latitude"]

0       37.37
1       34.26
2       33.78
3       33.82
4       36.33
        ...
2995    34.42
2996    34.06
2997    36.30
2998    34.10
2999    34.42
Name: latitude, Length: 3000, dtype: float64