<a href="https://colab.research.google.com/github/abubakar1109/Full-Stack-Data-Scientist-BootCamp/blob/main/MODULE%204%3A%20NumPy%20%26%20Pandas/Pandas_Abubakar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import Library

In [61]:
import pandas as pd
import numpy as np

Series

In [62]:
myfirends=['Abubakar','Ahmad','Arayash','Taha','Mughal','Basil']
myfirends

['Abubakar', 'Ahmad', 'Arayash', 'Taha', 'Mughal', 'Basil']

In [63]:
pd.Series(myfirends)

0    Abubakar
1       Ahmad
2     Arayash
3        Taha
4      Mughal
5       Basil
dtype: object

Creating our own index on Series

In [64]:
mydays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
mydays

['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']

In [65]:
pd.Series(mydays)

0       Monday
1      Tuesday
2    Wednesday
3     Thursday
4       Friday
5     Saturday
dtype: object

In [66]:
pd.Series(myfirends, index=mydays)

Monday       Abubakar
Tuesday         Ahmad
Wednesday     Arayash
Thursday         Taha
Friday         Mughal
Saturday        Basil
dtype: object

In [67]:
days=pd.Series(['Monday','Tuesday','Wednesday','Thursday','Friday'], index=['Day 1','Day 2','Day 3','Day 4','Day 5'])
days

Day 1       Monday
Day 2      Tuesday
Day 3    Wednesday
Day 4     Thursday
Day 5       Friday
dtype: object

In [68]:
friends=pd.Series(['Abubakar','Ahmad','Arayash','Taha','Mughal','Basil'])

In [69]:
days=pd.Series(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'])

Concatenation

In [70]:
days+" "+friends

0      Monday Abubakar
1        Tuesday Ahmad
2    Wednesday Arayash
3        Thursday Taha
4        Friday Mughal
5       Saturday Basil
dtype: object

Split Function

In [71]:
days=pd.Series(['Monday','Tuesday','Wednesday','Thursday','Friday'], index='Day1 Day2 Day3 Day4 Day5'.split())
days

Day1       Monday
Day2      Tuesday
Day3    Wednesday
Day4     Thursday
Day5       Friday
dtype: object

In [72]:
friends=pd.Series(['Abubakar','Ahmad','basil','taha','Mughal'], index='Day1,Day2,Day3,Day4,Day5'.split(','))
friends

Day1    Abubakar
Day2       Ahmad
Day3       basil
Day4        taha
Day5      Mughal
dtype: object

In [73]:
days+' '+friends

Day1    Monday Abubakar
Day2      Tuesday Ahmad
Day3    Wednesday basil
Day4      Thursday taha
Day5      Friday Mughal
dtype: object

In [74]:
days['Day4']

'Thursday'

Loc & ILoc

In [75]:
friend={
    'abubakar':'hassanabdal',
    'taha':'wah',
    'ahmad':'overseas',
    'mughal':'chor',
    'basil':'bahria'
}
friend_series=pd.Series(friend)
friend_series

abubakar    hassanabdal
taha                wah
ahmad          overseas
mughal             chor
basil            bahria
dtype: object

In [76]:
friend_series.loc['ahmad']

'overseas'

In [77]:
friend_series.iloc[2]

'overseas'

In [78]:
friend_series[2]

/tmp/ipykernel_280/2735768739.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  friend_series[2]

'overseas'

DataFrame

In [79]:
np.random.rand(10,5)

array([[0.8860282 , 0.16316561, 0.10760621, 0.93944052, 0.88316354],
       [0.36217038, 0.11640369, 0.21276973, 0.06358846, 0.13250743],
       [0.10604166, 0.19885177, 0.73621736, 0.9778209 , 0.25667389],
       [0.58596964, 0.75526352, 0.95087261, 0.45193957, 0.04066623],
       [0.83749474, 0.86456599, 0.22488456, 0.06722765, 0.25811257],
       [0.60463121, 0.34772127, 0.7630856 , 0.79099095, 0.10040693],
       [0.3245071 , 0.89466639, 0.7028715 , 0.64469163, 0.64285385],
       [0.59092312, 0.60118926, 0.48595137, 0.86486146, 0.07624298],
       [0.12547626, 0.3940361 , 0.94410001, 0.52588916, 0.48449431],
       [0.06265143, 0.2050767 , 0.82283784, 0.52576635, 0.89686454]])

In [80]:
df=pd.DataFrame(np.random.rand(10,5))
df

          0         1         2         3         4
0  0.273672  0.182038  0.085705  0.520132  0.937752
1  0.822539  0.696517  0.129883  0.882997  0.973729
2  0.458605  0.239845  0.189906  0.461712  0.581252
3  0.916756  0.685238  0.835301  0.790580  0.364389
4  0.202967  0.806057  0.371582  0.741320  0.680111
5  0.313197  0.026686  0.060492  0.468396  0.154843
6  0.078311  0.190052  0.116684  0.934993  0.940925
7  0.034389  0.795435  0.321951  0.427565  0.890247
8  0.970356  0.583878  0.006151  0.608030  0.455922
9  0.221714  0.929798  0.010597  0.460819  0.898333

In [81]:
ex_df=pd.DataFrame(np.random.rand(10,5), index='R1 R2 R3 R4 R5 R6 R7 R8 R9 R10'.split(), columns='C1 C2 C3 C4 C5'.split())
ex_df

           C1        C2        C3        C4        C5
R1   0.820628  0.041075  0.383218  0.844063  0.361076
R2   0.757743  0.264391  0.818119  0.889342  0.068555
R3   0.641370  0.432704  0.987001  0.750883  0.195993
R4   0.978380  0.954114  0.110417  0.976078  0.767691
R5   0.601788  0.657827  0.188334  0.611971  0.423911
R6   0.563437  0.149318  0.669925  0.008727  0.728432
R7   0.327773  0.975927  0.418834  0.608757  0.999671
R8   0.444504  0.336500  0.319015  0.410967  0.319250
R9   0.503012  0.945059  0.534569  0.587317  0.759742
R10  0.890234  0.730312  0.156722  0.557554  0.955653

Indexing & Selection

In [82]:
ex_df['C5']

R1     0.361076
R2     0.068555
R3     0.195993
R4     0.767691
R5     0.423911
R6     0.728432
R7     0.999671
R8     0.319250
R9     0.759742
R10    0.955653
Name: C5, dtype: float64

In [83]:
ex_df[['C2','C4']]

           C2        C4
R1   0.041075  0.844063
R2   0.264391  0.889342
R3   0.432704  0.750883
R4   0.954114  0.976078
R5   0.657827  0.611971
R6   0.149318  0.008727
R7   0.975927  0.608757
R8   0.336500  0.410967
R9   0.945059  0.587317
R10  0.730312  0.557554

Working with Dataset

In [84]:
cat Automobile_data.csv

symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height,curb-weight,engine-type,num-of-cylinders,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9,111,5000,21,27,13495
3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8,2548,dohc,four,130,mpfi,3.47,2.68,9,111,5000,21,27,16500
1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4,2823,ohcv,six,152,mpfi,2.68,3.47,9,154,5000,19,26,16500
2,164,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3,2337,ohc,four,109,mpfi,3.19,3.4,10,102,5500,24,30,13950
2,164,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3,2824,ohc,five,136,mpfi,3.19,3.4,8,115,5500,18,22,17450
2,?,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1,2507,ohc,five,136,mpfi,3.19,3.4,8.5,110,5500,19,25,15250
1,158,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7,2844,ohc,five,136,mpfi,3.19,3.4,8.5,110,5500,19,25,17710
1,?,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7,2954,ohc,five,136,mpfi,3.19,3.4,8.5,110,5500,19,25,18920
1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9,3086,ohc,five,131,mpfi,3.13,3.4,8.3,140,5500,17,20,23875
0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,52,3053,ohc,five,131,mpfi,3.13,3.4,7,160,5500,16,22,?
2,192,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16430
0,192,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,2395,ohc,four,108,mpfi,3.5,2.8,8.8,101,5800,23,29,16925
0,188,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3,2710,ohc,six,164,mpfi,3.31,3.19,9,121,4250,21,28,20970
0,188,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3,2765,ohc,six,164,mpfi,3.31,3.19,9,121,4250,21,28,21105
1,?,bmw,gas,std,four,sedan,rwd,front,103.5,189,66.9,55.7,3055,ohc,six,164,mpfi,3.31,3.19,9,121,4250,20,25,24565
0,?,bmw,gas,std,four,sedan,rwd,front,103.5,189,66.9,55.7,3230,ohc,six,209,mpfi,3.62,3.39,8,182,5400,16,22,30760
0,?,bmw,gas,std,two,sedan,rwd,front,103.5,193.8,67.9,53.7,3380,ohc,six,209,mpfi,3.62,3.39,8,182,5400,16,22,41315
0,?,bmw,gas,std,four,sedan,rwd,front,110,197,70.9,56.3,3505,ohc,six,209,mpfi,3.62,3.39,8,182,5400,15,20,36880
2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,141.1,60.3,53.2,1488,l,three,61,2bbl,2.91,3.03,9.5,48,5100,47,53,5151
1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,155.9,63.6,52,1874,ohc,four,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6295
0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,158.8,63.6,52,1909,ohc,four,90,2bbl,3.03,3.11,9.6,70,5400,38,43,6575
1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,157.3,63.8,50.8,1876,ohc,four,90,2bbl,2.97,3.23,9.41,68,5500,37,41,5572
1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,157.3,63.8,50.8,1876,ohc,four,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6377
1,118,dodge,gas,turbo,two,hatchback,fwd,front,93.7,157.3,63.8,50.8,2128,ohc,four,98,mpfi,3.03,3.39,7.6,102,5500,24,30,7957
1,148,dodge,gas,std,four,hatchback,fwd,front,93.7,157.3,63.8,50.6,1967,ohc,four,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6229
1,148,dodge,gas,std,four,sedan,fwd,front,93.7,157.3,63.8,50.6,1989,ohc,four,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6692
1,148,dodge,gas,std,four,sedan,fwd,front,93.7,157.3,63.8,50.6,1989,ohc,four,90,2bbl,2.97,3.23,9.4,68,5500,31,38,7609
1,148,dodge,gas,turbo,?,sedan,fwd,front,93.7,157.3,63.8,50.6,2191,ohc,four,98,mpfi,3.03,3.39,7.6,102,5500,24,30,8558
-1,110,dodge,gas,std,four,wagon,fwd,front,103.3,174.6,64.6,59.8,2535,ohc,four,122,2bbl,3.34,3.46,8.5,88,5000,24,30,8921
3,145,dodge,gas,turbo,two,hatchback,fwd,front,95.9,173.2,66.3,50.2,2811,ohc,four,156,mfi,3.6,3.9,7,145,5000,19,24,12964
2,137,honda,gas,std,two,hatchback,fwd,front,86.6,144.6,63.9,50.8,1713,ohc,four,92,1bbl,2.91,3.41,9.6,58,4800,49,54,6479
2,137,honda,gas,std,two,hatchback,fwd,front,86.6,144.6,63.9,50.8,1819,ohc,four,92,1bbl,2.91,3.41,9.2,76,6000,31,38,6855
1,101,honda,gas,std,two,hatchback,fwd,front,93.7,150,64,52.6,1837,ohc,four,79,1bbl,2.91,3.07,10.1,60,5500,38,42,5399
1,101,honda,gas,std,two,hatchback,fwd,front,93.7,150,64,52.6,1940,ohc,four,92,1bbl,2.91,3.41,9.2,76,6000,30,34,6529
1,101,honda,gas,std,two,hatchback,fwd,front,93.7,150,64,52.6,1956,ohc,four,92,1bbl,2.91,3.41,9.2,76,6000,30,34,7129
0,110,honda,gas,std,four,sedan,fwd,front,96.5,163.4,64,54.5,2010,ohc,four,92,1bbl,2.91,3.41,9.2,76,6000,30,34,7295
0,78,honda,gas,std,four,wagon,fwd,front,96.5,157.1,63.9,58.3,2024,ohc,four,92,1bbl,2.92,3.41,9.2,76,6000,30,34,7295
0,106,honda,gas,std,two,hatchback,fwd,front,96.5,167.5,65.2,53.3,2236,ohc,four,110,1bbl,3.15,3.58,9,86,5800,27,33,7895
0,106,honda,gas,std,two,hatchback,fwd,front,96.5,167.5,65.2,53.3,2289,ohc,four,110,1bbl,3.15,3.58,9,86,5800,27,33,9095
0,85,honda,gas,std,four,sedan,fwd,front,96.5,175.4,65.2,54.1,2304,ohc,four,110,1bbl,3.15,3.58,9,86,5800,27,33,8845
0,85,honda,gas,std,four,sedan,fwd,front,96.5,175.4,62.5,54.1,2372,ohc,four,110,1bbl,3.15,3.58,9,86,5800,27,33,10295
0,85,honda,gas,std,four,sedan,fwd,front,96.5,175.4,65.2,54.1,2465,ohc,four,110,mpfi,3.15,3.58,9,101,5800,24,28,12945
1,107,honda,gas,std,two,sedan,fwd,front,96.5,169.1,66,51,2293,ohc,four,110,2bbl,3.15,3.58,9.1,100,5500,25,31,10345
0,?,isuzu,gas,std,four,sedan,rwd,front,94.3,170.7,61.8,53.5,2337,ohc,four,111,2bbl,3.31,3.23,8.5,78,4800,24,29,6785
1,?,isuzu,gas,std,two,sedan,fwd,front,94.5,155.9,63.6,52,1874,ohc,four,90,2bbl,3.03,3.11,9.6,70,5400,38,43,?
0,?,isuzu,gas,std,four,sedan,fwd,front,94.5,155.9,63.6,52,1909,ohc,four,90,2bbl,3.03,3.11,9.6,70,5400,38,43,?
2,?,isuzu,gas,std,two,hatchback,rwd,front,96,172.6,65.2,51.4,2734,ohc,four,119,spfi,3.43,3.23,9.2,90,5000,24,29,11048
0,145,jaguar,gas,std,four,sedan,rwd,front,113,199.6,69.6,52.8,4066,dohc,six,258,mpfi,3.63,4.17,8.1,176,4750,15,19,32250
0,?,jaguar,gas,std,four,sedan,rwd,front,113,199.6,69.6,52.8,4066,dohc,six,258,mpfi,3.63,4.17,8.1,176,4750,15,19,35550
0,?,jaguar,gas,std,two,sedan,rwd,front,102,191.7,70.6,47.8,3950,ohcv,twelve,326,mpfi,3.54,2.76,11.5,262,5000,13,17,36000
1,104,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,64.2,54.1,1890,ohc,four,91,2bbl,3.03,3.15,9,68,5000,30,31,5195
1,104,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,64.2,54.1,1900,ohc,four,91,2bbl,3.03,3.15,9,68,5000,31,38,6095
1,104,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,64.2,54.1,1905,ohc,four,91,2bbl,3.03,3.15,9,68,5000,31,38,6795
1,113,mazda,gas,std,four,sedan,fwd,front,93.1,166.8,64.2,54.1,1945,ohc,four,91,2bbl,3.03,3.15,9,68,5000,31,38,6695
1,113,mazda,gas,std,four,sedan,fwd,front,93.1,166.8,64.2,54.1,1950,ohc,four,91,2bbl,3.08,3.15,9,68,5000,31,38,7395
3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,169,65.7,49.6,2380,rotor,two,70,4bbl,?,?,9.4,101,6000,17,23,10945
3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,169,65.7,49.6,2380,rotor,two,70,4bbl,?,?,9.4,101,6000,17,23,11845
3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,169,65.7,49.6,2385,rotor,two,70,4bbl,?,?,9.4,101,6000,17,23,13645
3,150,mazda,gas,std,two,hatchback,rwd,front,95.3,169,65.7,49.6,2500,rotor,two,80,mpfi,?,?,9.4,135,6000,16,23,15645
1,129,mazda,gas,std,two,hatchback,fwd,front,98.8,177.8,66.5,53.7,2385,ohc,four,122,2bbl,3.39,3.39,8.6,84,4800,26,32,8845
0,115,mazda,gas,std,four,sedan,fwd,front,98.8,177.8,66.5,55.5,2410,ohc,four,122,2bbl,3.39,3.39,8.6,84,4800,26,32,8495
1,129,mazda,gas,std,two,hatchback,fwd,front,98.8,177.8,66.5,53.7,2385,ohc,four,122,2bbl,3.39,3.39,8.6,84,4800,26,32,10595
0,115,mazda,gas,std,four,sedan,fwd,front,98.8,177.8,66.5,55.5,2410,ohc,four,122,2bbl,3.39,3.39,8.6,84,4800,26,32,10245
0,?,mazda,diesel,std,?,sedan,fwd,front,98.8,177.8,66.5,55.5,2443,ohc,four,122,idi,3.39,3.39,22.7,64,4650,36,42,10795
0,115,mazda,gas,std,four,hatchback,fwd,front,98.8,177.8,66.5,55.5,2425,ohc,four,122,2bbl,3.39,3.39,8.6,84,4800,26,32,11245
0,118,mazda,gas,std,four,sedan,rwd,front,104.9,175,66.1,54.4,2670,ohc,four,140,mpfi,3.76,3.16,8,120,5000,19,27,18280
0,?,mazda,diesel,std,four,sedan,rwd,front,104.9,175,66.1,54.4,2700,ohc,four,134,idi,3.43,3.64,22,72,4200,31,39,18344
-1,93,mercedes-benz,diesel,turbo,four,sedan,rwd,front,110,190.9,70.3,56.5,3515,ohc,five,183,idi,3.58,3.64,21.5,123,4350,22,25,25552
-1,93,mercedes-benz,diesel,turbo,four,wagon,rwd,front,110,190.9,70.3,58.7,3750,ohc,five,183,idi,3.58,3.64,21.5,123,4350,22,25,28248
0,93,mercedes-benz,diesel,turbo,two,hardtop,rwd,front,106.7,187.5,70.3,54.9,3495,ohc,five,183,idi,3.58,3.64,21.5,123,4350,22,25,28176
-1,93,mercedes-benz,diesel,turbo,four,sedan,rwd,front,115.6,202.6,71.7,56.3,3770,ohc,five,183,idi,3.58,3.64,21.5,123,4350,22,25,31600
-1,?,mercedes-benz,gas,std,four,sedan,rwd,front,115.6,202.6,71.7,56.5,3740,ohcv,eight,234,mpfi,3.46,3.1,8.3,155,4750,16,18,34184
3,142,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,180.3,70.5,50.8,3685,ohcv,eight,234,mpfi,3.46,3.1,8.3,155,4750,16,18,35056
0,?,mercedes-benz,gas,std,four,sedan,rwd,front,120.9,208.1,71.7,56.7,3900,ohcv,eight,308,mpfi,3.8,3.35,8,184,4500,14,16,40960
1,?,mercedes-benz,gas,std,two,hardtop,rwd,front,112,199.2,72,55.4,3715,ohcv,eight,304,mpfi,3.8,3.35,8,184,4500,14,16,45400
1,?,mercury,gas,turbo,two,hatchback,rwd,front,102.7,178.4,68,54.8,2910,ohc,four,140,mpfi,3.78,3.12,8,175,5000,19,24,16503
2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,157.3,64.4,50.8,1918,ohc,four,92,2bbl,2.97,3.23,9.4,68,5500,37,41,5389
2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,157.3,64.4,50.8,1944,ohc,four,92,2bbl,2.97,3.23,9.4,68,5500,31,38,6189
2,161,mitsubishi,gas,std,two,hatchback,fwd,front,93.7,157.3,64.4,50.8,2004,ohc,four,92,2bbl,2.97,3.23,9.4,68,5500,31,38,6669
1,161,mitsubishi,gas,turbo,two,hatchback,fwd,front,93,157.3,63.8,50.8,2145,ohc,four,98,spdi,3.03,3.39,7.6,102,5500,24,30,7689
3,153,mitsubishi,gas,turbo,two,hatchback,fwd,front,96.3,173,65.4,49.4,2370,ohc,four,110,spdi,3.17,3.46,7.5,116,5500,23,30,9959
3,153,mitsubishi,gas,std,two,hatchback,fwd,front,96.3,173,65.4,49.4,2328,ohc,four,122,2bbl,3.35,3.46,8.5,88,5000,25,32,8499
3,?,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,173.2,66.3,50.2,2833,ohc,four,156,spdi,3.58,3.86,7,145,5000,19,24,12629
3,?,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,173.2,66.3,50.2,2921,ohc,four,156,spdi,3.59,3.86,7,145,5000,19,24,14869
3,?,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,173.2,66.3,50.2,2926,ohc,four,156,spdi,3.59,3.86,7,145,5000,19,24,14489
1,125,mitsubishi,gas,std,four,sedan,fwd,front,96.3,172.4,65.4,51.6,2365,ohc,four,122,2bbl,3.35,3.46,8.5,88,5000,25,32,6989
1,125,mitsubishi,gas,std,four,sedan,fwd,front,96.3,172.4,65.4,51.6,2405,ohc,four,122,2bbl,3.35,3.46,8.5,88,5000,25,32,8189
1,125,mitsubishi,gas,turbo,four,sedan,fwd,front,96.3,172.4,65.4,51.6,2403,ohc,four,110,spdi,3.17,3.46,7.5,116,5500,23,30,9279
-1,137,mitsubishi,gas,std,four,sedan,fwd,front,96.3,172.4,65.4,51.6,2403,ohc,four,110,spdi,3.17,3.46,7.5,116,5500,23,30,9279
1,128,nissan,gas,std,two,sedan,fwd,front,94.5,165.3,63.8,54.5,1889,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,5499
1,128,nissan,diesel,std,two,sedan,fwd,front,94.5,165.3,63.8,54.5,2017,ohc,four,103,idi,2.99,3.47,21.9,55,4800,45,50,7099
1,128,nissan,gas,std,two,sedan,fwd,front,94.5,165.3,63.8,54.5,1918,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6649
1,122,nissan,gas,std,four,sedan,fwd,front,94.5,165.3,63.8,54.5,1938,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,6849
1,103,nissan,gas,std,four,wagon,fwd,front,94.5,170.2,63.8,53.5,2024,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7349
1,128,nissan,gas,std,two,sedan,fwd,front,94.5,165.3,63.8,54.5,1951,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7299
1,128,nissan,gas,std,two,hatchback,fwd,front,94.5,165.6,63.8,53.3,2028,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7799
1,122,nissan,gas,std,four,sedan,fwd,front,94.5,165.3,63.8,54.5,1971,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7499
1,103,nissan,gas,std,four,wagon,fwd,front,94.5,170.2,63.8,53.5,2037,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,7999
2,168,nissan,gas,std,two,hardtop,fwd,front,95.1,162.4,63.8,53.3,2008,ohc,four,97,2bbl,3.15,3.29,9.4,69,5200,31,37,8249
0,106,nissan,gas,std,four,hatchback,fwd,front,97.2,173.4,65.2,54.7,2324,ohc,four,120,2bbl,3.33,3.47,8.5,97,5200,27,34,8949
0,106,nissan,gas,std,four,sedan,fwd,front,97.2,173.4,65.2,54.7,2302,ohc,four,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
0,128,nissan,gas,std,four,sedan,fwd,front,100.4,181.7,66.5,55.1,3095,ohcv,six,181,mpfi,3.43,3.27,9,152,5200,17,22,13499
0,108,nissan,gas,std,four,wagon,fwd,front,100.4,184.6,66.5,56.1,3296,ohcv,six,181,mpfi,3.43,3.27,9,152,5200,17,22,14399
0,108,nissan,gas,std,four,sedan,fwd,front,100.4,184.6,66.5,55.1,3060,ohcv,six,181,mpfi,3.43,3.27,9,152,5200,19,25,13499
3,194,nissan,gas,std,two,hatchback,rwd,front,91.3,170.7,67.9,49.7,3071,ohcv,six,181,mpfi,3.43,3.27,9,160,5200,19,25,17199
3,194,nissan,gas,turbo,two,hatchback,rwd,front,91.3,170.7,67.9,49.7,3139,ohcv,six,181,mpfi,3.43,3.27,7.8,200,5200,17,23,19699
1,231,nissan,gas,std,two,hatchback,rwd,front,99.2,178.5,67.9,49.7,3139,ohcv,six,181,mpfi,3.43,3.27,9,160,5200,19,25,18399
0,161,peugot,gas,std,four,sedan,rwd,front,107.9,186.7,68.4,56.7,3020,l,four,120,mpfi,3.46,3.19,8.4,97,5000,19,24,11900
0,161,peugot,diesel,turbo,four,sedan,rwd,front,107.9,186.7,68.4,56.7,3197,l,four,152,idi,3.7,3.52,21,95,4150,28,33,13200
0,?,peugot,gas,std,four,wagon,rwd,front,114.2,198.9,68.4,58.7,3230,l,four,120,mpfi,3.46,3.19,8.4,97,5000,19,24,12440
0,?,peugot,diesel,turbo,four,wagon,rwd,front,114.2,198.9,68.4,58.7,3430,l,four,152,idi,3.7,3.52,21,95,4150,25,25,13860
0,161,peugot,gas,std,four,sedan,rwd,front,107.9,186.7,68.4,56.7,3075,l,four,120,mpfi,3.46,2.19,8.4,95,5000,19,24,15580
0,161,peugot,diesel,turbo,four,sedan,rwd,front,107.9,186.7,68.4,56.7,3252,l,four,152,idi,3.7,3.52,21,95,4150,28,33,16900
0,?,peugot,gas,std,four,wagon,rwd,front,114.2,198.9,68.4,56.7,3285,l,four,120,mpfi,3.46,2.19,8.4,95,5000,19,24,16695
0,?,peugot,diesel,turbo,four,wagon,rwd,front,114.2,198.9,68.4,58.7,3485,l,four,152,idi,3.7,3.52,21,95,4150,25,25,17075
0,161,peugot,gas,std,four,sedan,rwd,front,107.9,186.7,68.4,56.7,3075,l,four,120,mpfi,3.46,3.19,8.4,97,5000,19,24,16630
0,161,peugot,diesel,turbo,four,sedan,rwd,front,107.9,186.7,68.4,56.7,3252,l,four,152,idi,3.7,3.52,21,95,4150,28,33,17950
0,161,peugot,gas,turbo,four,sedan,rwd,front,108,186.7,68.3,56,3130,l,four,134,mpfi,3.61,3.21,7,142,5600,18,24,18150
1,119,plymouth,gas,std,two,hatchback,fwd,front,93.7,157.3,63.8,50.8,1918,ohc,four,90,2bbl,2.97,3.23,9.4,68,5500,37,41,5572
1,119,plymouth,gas,turbo,two,hatchback,fwd,front,93.7,157.3,63.8,50.8,2128,ohc,four,98,spdi,3.03,3.39,7.6,102,5500,24,30,7957
1,154,plymouth,gas,std,four,hatchback,fwd,front,93.7,157.3,63.8,50.6,1967,ohc,four,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6229
1,154,plymouth,gas,std,four,sedan,fwd,front,93.7,167.3,63.8,50.8,1989,ohc,four,90,2bbl,2.97,3.23,9.4,68,5500,31,38,6692
1,154,plymouth,gas,std,four,sedan,fwd,front,93.7,167.3,63.8,50.8,2191,ohc,four,98,2bbl,2.97,3.23,9.4,68,5500,31,38,7609
-1,74,plymouth,gas,std,four,wagon,fwd,front,103.3,174.6,64.6,59.8,2535,ohc,four,122,2bbl,3.35,3.46,8.5,88,5000,24,30,8921
3,?,plymouth,gas,turbo,two,hatchback,rwd,front,95.9,173.2,66.3,50.2,2818,ohc,four,156,spdi,3.59,3.86,7,145,5000,19,24,12764
3,186,porsche,gas,std,two,hatchback,rwd,front,94.5,168.9,68.3,50.2,2778,ohc,four,151,mpfi,3.94,3.11,9.5,143,5500,19,27,22018
3,?,porsche,gas,std,two,hardtop,rwd,rear,89.5,168.9,65,51.6,2756,ohcf,six,194,mpfi,3.74,2.9,9.5,207,5900,17,25,32528
3,?,porsche,gas,std,two,hardtop,rwd,rear,89.5,168.9,65,51.6,2756,ohcf,six,194,mpfi,3.74,2.9,9.5,207,5900,17,25,34028
3,?,porsche,gas,std,two,convertible,rwd,rear,89.5,168.9,65,51.6,2800,ohcf,six,194,mpfi,3.74,2.9,9.5,207,5900,17,25,37028
1,?,porsche,gas,std,two,hatchback,rwd,front,98.4,175.7,72.3,50.5,3366,dohcv,eight,203,mpfi,3.94,3.11,10,288,5750,17,28,?
0,?,renault,gas,std,four,wagon,fwd,front,96.1,181.5,66.5,55.2,2579,ohc,four,132,mpfi,3.46,3.9,8.7,?,?,23,31,9295
2,?,renault,gas,std,two,hatchback,fwd,front,96.1,176.8,66.6,50.5,2460,ohc,four,132,mpfi,3.46,3.9,8.7,?,?,23,31,9895
3,150,saab,gas,std,two,hatchback,fwd,front,99.1,186.6,66.5,56.1,2658,ohc,four,121,mpfi,3.54,3.07,9.31,110,5250,21,28,11850
2,104,saab,gas,std,four,sedan,fwd,front,99.1,186.6,66.5,56.1,2695,ohc,four,121,mpfi,3.54,3.07,9.3,110,5250,21,28,12170
3,150,saab,gas,std,two,hatchback,fwd,front,99.1,186.6,66.5,56.1,2707,ohc,four,121,mpfi,2.54,2.07,9.3,110,5250,21,28,15040
2,104,saab,gas,std,four,sedan,fwd,front,99.1,186.6,66.5,56.1,2758,ohc,four,121,mpfi,3.54,3.07,9.3,110,5250,21,28,15510
3,150,saab,gas,turbo,two,hatchback,fwd,front,99.1,186.6,66.5,56.1,2808,dohc,four,121,mpfi,3.54,3.07,9,160,5500,19,26,18150
2,104,saab,gas,turbo,four,sedan,fwd,front,99.1,186.6,66.5,56.1,2847,dohc,four,121,mpfi,3.54,3.07,9,160,5500,19,26,18620
2,83,subaru,gas,std,two,hatchback,fwd,front,93.7,156.9,63.4,53.7,2050,ohcf,four,97,2bbl,3.62,2.36,9,69,4900,31,36,5118
2,83,subaru,gas,std,two,hatchback,fwd,front,93.7,157.9,63.6,53.7,2120,ohcf,four,108,2bbl,3.62,2.64,8.7,73,4400,26,31,7053
2,83,subaru,gas,std,two,hatchback,4wd,front,93.3,157.3,63.8,55.7,2240,ohcf,four,108,2bbl,3.62,2.64,8.7,73,4400,26,31,7603
0,102,subaru,gas,std,four,sedan,fwd,front,97.2,172,65.4,52.5,2145,ohcf,four,108,2bbl,3.62,2.64,9.5,82,4800,32,37,7126
0,102,subaru,gas,std,four,sedan,fwd,front,97.2,172,65.4,52.5,2190,ohcf,four,108,2bbl,3.62,2.64,9.5,82,4400,28,33,7775
0,102,subaru,gas,std,four,sedan,fwd,front,97.2,172,65.4,52.5,2340,ohcf,four,108,mpfi,3.62,2.64,9,94,5200,26,32,9960
0,102,subaru,gas,std,four,sedan,4wd,front,97,172,65.4,54.3,2385,ohcf,four,108,2bbl,3.62,2.64,9,82,4800,24,25,9233
0,102,subaru,gas,turbo,four,sedan,4wd,front,97,172,65.4,54.3,2510,ohcf,four,108,mpfi,3.62,2.64,7.7,111,4800,24,29,11259
0,89,subaru,gas,std,four,wagon,fwd,front,97,173.5,65.4,53,2290,ohcf,four,108,2bbl,3.62,2.64,9,82,4800,28,32,7463
0,89,subaru,gas,std,four,wagon,fwd,front,97,173.5,65.4,53,2455,ohcf,four,108,mpfi,3.62,2.64,9,94,5200,25,31,10198
0,85,subaru,gas,std,four,wagon,4wd,front,96.9,173.6,65.4,54.9,2420,ohcf,four,108,2bbl,3.62,2.64,9,82,4800,23,29,8013
0,85,subaru,gas,turbo,four,wagon,4wd,front,96.9,173.6,65.4,54.9,2650,ohcf,four,108,mpfi,3.62,2.64,7.7,111,4800,23,23,11694
1,87,toyota,gas,std,two,hatchback,fwd,front,95.7,158.7,63.6,54.5,1985,ohc,four,92,2bbl,3.05,3.03,9,62,4800,35,39,5348
1,87,toyota,gas,std,two,hatchback,fwd,front,95.7,158.7,63.6,54.5,2040,ohc,four,92,2bbl,3.05,3.03,9,62,4800,31,38,6338
1,74,toyota,gas,std,four,hatchback,fwd,front,95.7,158.7,63.6,54.5,2015,ohc,four,92,2bbl,3.05,3.03,9,62,4800,31,38,6488
0,77,toyota,gas,std,four,wagon,fwd,front,95.7,169.7,63.6,59.1,2280,ohc,four,92,2bbl,3.05,3.03,9,62,4800,31,37,6918
0,81,toyota,gas,std,four,wagon,4wd,front,95.7,169.7,63.6,59.1,2290,ohc,four,92,2bbl,3.05,3.03,9,62,4800,27,32,7898
0,91,toyota,gas,std,four,wagon,4wd,front,95.7,169.7,63.6,59.1,3110,ohc,four,92,2bbl,3.05,3.03,9,62,4800,27,32,8778
0,91,toyota,gas,std,four,sedan,fwd,front,95.7,166.3,64.4,53,2081,ohc,four,98,2bbl,3.19,3.03,9,70,4800,30,37,6938
0,91,toyota,gas,std,four,hatchback,fwd,front,95.7,166.3,64.4,52.8,2109,ohc,four,98,2bbl,3.19,3.03,9,70,4800,30,37,7198
0,91,toyota,diesel,std,four,sedan,fwd,front,95.7,166.3,64.4,53,2275,ohc,four,110,idi,3.27,3.35,22.5,56,4500,34,36,7898
0,91,toyota,diesel,std,four,hatchback,fwd,front,95.7,166.3,64.4,52.8,2275,ohc,four,110,idi,3.27,3.35,22.5,56,4500,38,47,7788
0,91,toyota,gas,std,four,sedan,fwd,front,95.7,166.3,64.4,53,2094,ohc,four,98,2bbl,3.19,3.03,9,70,4800,38,47,7738
0,91,toyota,gas,std,four,hatchback,fwd,front,95.7,166.3,64.4,52.8,2122,ohc,four,98,2bbl,3.19,3.03,9,70,4800,28,34,8358
0,91,toyota,gas,std,four,sedan,fwd,front,95.7,166.3,64.4,52.8,2140,ohc,four,98,2bbl,3.19,3.03,9,70,4800,28,34,9258
1,168,toyota,gas,std,two,sedan,rwd,front,94.5,168.7,64,52.6,2169,ohc,four,98,2bbl,3.19,3.03,9,70,4800,29,34,8058
1,168,toyota,gas,std,two,hatchback,rwd,front,94.5,168.7,64,52.6,2204,ohc,four,98,2bbl,3.19,3.03,9,70,4800,29,34,8238

In [85]:
data=pd.read_csv("/content/Automobile_data.csv")

In [86]:
data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [87]:
data.tail()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

Adding a Column to DataFrame

In [88]:
ex_df['C6']=ex_df['C5']*2

In [89]:
ex_df

           C1        C2        C3        C4        C5        C6
R1   0.820628  0.041075  0.383218  0.844063  0.361076  0.722151
R2   0.757743  0.264391  0.818119  0.889342  0.068555  0.137111
R3   0.641370  0.432704  0.987001  0.750883  0.195993  0.391986
R4   0.978380  0.954114  0.110417  0.976078  0.767691  1.535382
R5   0.601788  0.657827  0.188334  0.611971  0.423911  0.847822
R6   0.563437  0.149318  0.669925  0.008727  0.728432  1.456863
R7   0.327773  0.975927  0.418834  0.608757  0.999671  1.999343
R8   0.444504  0.336500  0.319015  0.410967  0.319250  0.638500
R9   0.503012  0.945059  0.534569  0.587317  0.759742  1.519485
R10  0.890234  0.730312  0.156722  0.557554  0.955653  1.911307

In [90]:
type(ex_df['C6'])

pandas.core.series.Series

Drop Columns in DataFrame

In [91]:
ex_df.drop('C6', axis=1)

           C1        C2        C3        C4        C5
R1   0.820628  0.041075  0.383218  0.844063  0.361076
R2   0.757743  0.264391  0.818119  0.889342  0.068555
R3   0.641370  0.432704  0.987001  0.750883  0.195993
R4   0.978380  0.954114  0.110417  0.976078  0.767691
R5   0.601788  0.657827  0.188334  0.611971  0.423911
R6   0.563437  0.149318  0.669925  0.008727  0.728432
R7   0.327773  0.975927  0.418834  0.608757  0.999671
R8   0.444504  0.336500  0.319015  0.410967  0.319250
R9   0.503012  0.945059  0.534569  0.587317  0.759742
R10  0.890234  0.730312  0.156722  0.557554  0.955653

In [92]:
ex_df

           C1        C2        C3        C4        C5        C6
R1   0.820628  0.041075  0.383218  0.844063  0.361076  0.722151
R2   0.757743  0.264391  0.818119  0.889342  0.068555  0.137111
R3   0.641370  0.432704  0.987001  0.750883  0.195993  0.391986
R4   0.978380  0.954114  0.110417  0.976078  0.767691  1.535382
R5   0.601788  0.657827  0.188334  0.611971  0.423911  0.847822
R6   0.563437  0.149318  0.669925  0.008727  0.728432  1.456863
R7   0.327773  0.975927  0.418834  0.608757  0.999671  1.999343
R8   0.444504  0.336500  0.319015  0.410967  0.319250  0.638500
R9   0.503012  0.945059  0.534569  0.587317  0.759742  1.519485
R10  0.890234  0.730312  0.156722  0.557554  0.955653  1.911307

In [93]:
ex_df.drop('C6', axis=1,inplace=True)

In [94]:
ex_df

           C1        C2        C3        C4        C5
R1   0.820628  0.041075  0.383218  0.844063  0.361076
R2   0.757743  0.264391  0.818119  0.889342  0.068555
R3   0.641370  0.432704  0.987001  0.750883  0.195993
R4   0.978380  0.954114  0.110417  0.976078  0.767691
R5   0.601788  0.657827  0.188334  0.611971  0.423911
R6   0.563437  0.149318  0.669925  0.008727  0.728432
R7   0.327773  0.975927  0.418834  0.608757  0.999671
R8   0.444504  0.336500  0.319015  0.410967  0.319250
R9   0.503012  0.945059  0.534569  0.587317  0.759742
R10  0.890234  0.730312  0.156722  0.557554  0.955653

Droping a Row in DataFrame

In [95]:
ex_df.drop('R6',axis=0,inplace=True)

In [96]:
ex_df

           C1        C2        C3        C4        C5
R1   0.820628  0.041075  0.383218  0.844063  0.361076
R2   0.757743  0.264391  0.818119  0.889342  0.068555
R3   0.641370  0.432704  0.987001  0.750883  0.195993
R4   0.978380  0.954114  0.110417  0.976078  0.767691
R5   0.601788  0.657827  0.188334  0.611971  0.423911
R7   0.327773  0.975927  0.418834  0.608757  0.999671
R8   0.444504  0.336500  0.319015  0.410967  0.319250
R9   0.503012  0.945059  0.534569  0.587317  0.759742
R10  0.890234  0.730312  0.156722  0.557554  0.955653

In [97]:
ex_df.iloc[1]

C1    0.757743
C2    0.264391
C3    0.818119
C4    0.889342
C5    0.068555
Name: R2, dtype: float64

In [98]:
ex_df.loc['R2','C2']

np.float64(0.2643909100400885)

Reset Index in DataFrame

In [99]:
ex_df.index

Index(['R1', 'R2', 'R3', 'R4', 'R5', 'R7', 'R8', 'R9', 'R10'], dtype='object')

In [100]:
ex_df['spin']=['sp1','sp2','sp3','sp4','sp5','sp6','sp7','sp8','sp9']

In [101]:
ex_df

           C1        C2        C3        C4        C5 spin
R1   0.820628  0.041075  0.383218  0.844063  0.361076  sp1
R2   0.757743  0.264391  0.818119  0.889342  0.068555  sp2
R3   0.641370  0.432704  0.987001  0.750883  0.195993  sp3
R4   0.978380  0.954114  0.110417  0.976078  0.767691  sp4
R5   0.601788  0.657827  0.188334  0.611971  0.423911  sp5
R7   0.327773  0.975927  0.418834  0.608757  0.999671  sp6
R8   0.444504  0.336500  0.319015  0.410967  0.319250  sp7
R9   0.503012  0.945059  0.534569  0.587317  0.759742  sp8
R10  0.890234  0.730312  0.156722  0.557554  0.955653  sp9

In [102]:
ex_df.set_index('spin', inplace=True)

In [103]:
ex_df

            C1        C2        C3        C4        C5
spin
sp1   0.820628  0.041075  0.383218  0.844063  0.361076
sp2   0.757743  0.264391  0.818119  0.889342  0.068555
sp3   0.641370  0.432704  0.987001  0.750883  0.195993
sp4   0.978380  0.954114  0.110417  0.976078  0.767691
sp5   0.601788  0.657827  0.188334  0.611971  0.423911
sp6   0.327773  0.975927  0.418834  0.608757  0.999671
sp7   0.444504  0.336500  0.319015  0.410967  0.319250
sp8   0.503012  0.945059  0.534569  0.587317  0.759742
sp9   0.890234  0.730312  0.156722  0.557554  0.955653

Rename a Column in Pandas

In [104]:
ex_df.rename(columns={'C1':'first',
                      'C2':'second',
                      'C3':'third',
                      'C4':'fourth',
                      'C5':'fifth'}, inplace=True)

In [105]:
ex_df

         first    second     third    fourth     fifth
spin
sp1   0.820628  0.041075  0.383218  0.844063  0.361076
sp2   0.757743  0.264391  0.818119  0.889342  0.068555
sp3   0.641370  0.432704  0.987001  0.750883  0.195993
sp4   0.978380  0.954114  0.110417  0.976078  0.767691
sp5   0.601788  0.657827  0.188334  0.611971  0.423911
sp6   0.327773  0.975927  0.418834  0.608757  0.999671
sp7   0.444504  0.336500  0.319015  0.410967  0.319250
sp8   0.503012  0.945059  0.534569  0.587317  0.759742
sp9   0.890234  0.730312  0.156722  0.557554  0.955653

Select Specific Column in DataFrame

In [106]:
data['make']

0      alfa-romero
1      alfa-romero
2      alfa-romero
3             audi
4             audi
          ...
200          volvo
201          volvo
202          volvo
203          volvo
204          volvo
Name: make, Length: 205, dtype: object

In [107]:
data.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [108]:
data.index

RangeIndex(start=0, stop=205, step=1)

isnull() Vs Isna()

In [109]:
data.isnull()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [110]:
data.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

Drop Nan in dataset

In [111]:
data.dropna()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.4,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

Describe Function

In [112]:
data.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [113]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
symboling,205.0,0.834146,1.245307,-2.0,0.0,1.0,2.0,3.0
wheel-base,205.0,98.756585,6.021776,86.6,94.5,97.0,102.4,120.9
length,205.0,174.049268,12.337289,141.1,166.3,173.2,183.1,208.1
width,205.0,65.907805,2.145204,60.3,64.1,65.5,66.9,72.3
height,205.0,53.724878,2.443522,47.8,52.0,54.1,55.5,59.8
curb-weight,205.0,2555.565854,520.680204,1488.0,2145.0,2414.0,2935.0,4066.0
engine-size,205.0,126.907317,41.642693,61.0,97.0,120.0,141.0,326.0
compression-ratio,205.0,10.142537,3.972040,7.0,8.6,9.0,9.4,23.0
city-mpg,205.0,25.219512,6.542142,13.0,19.0,24.0,30.0,49.0
highway-mpg,205.0,30.751220,6.886443,16.0,25.0,30.0,34.0,54.0

Conditional Selection With Pandas

In [116]:
data['highway-mpg'].max()

54

In [125]:
data["highway-mpg"]>50

0      False
1      False
2      False
3      False
4      False
       ...
200    False
201    False
202    False
203    False
204    False
Name: highway-mpg, Length: 205, dtype: bool

In [126]:
data[data["highway-mpg"]>50][['make','price']]

         make price
18  chevrolet  5151
30      honda  6479

In [127]:
data[data['make']=='honda'][['make','price']]

     make  price
30  honda   6479
31  honda   6855
32  honda   5399
33  honda   6529
34  honda   7129
35  honda   7295
36  honda   7295
37  honda   7895
38  honda   9095
39  honda   8845
40  honda  10295
41  honda  12945
42  honda  10345

How To Deal With Null Values

In [130]:
df=pd.DataFrame({'value1':[100,np.nan,234,np.nan],
                 'value2':[300,121,np.nan,np.nan],
                 'value3':['XUI','VYU','NMA','IUY'],
                 })

In [131]:
df

   value1  value2 value3
0   100.0   300.0    XUI
1     NaN   121.0    VYU
2   234.0     NaN    NMA
3     NaN     NaN    IUY

In [132]:
df.isnull()

   value1  value2  value3
0   False   False   False
1    True   False   False
2   False    True   False
3    True    True   False

In [133]:
df.isna()

   value1  value2  value3
0   False   False   False
1    True   False   False
2   False    True   False
3    True    True   False

In [134]:
df.isna().sum()

value1    2
value2    2
value3    0
dtype: int64

In [138]:
df.fillna(df.mean(numeric_only=True), inplace=True)

In [139]:
df

   value1  value2 value3
0   100.0   300.0    XUI
1   167.0   121.0    VYU
2   234.0   210.5    NMA
3   167.0   210.5    IUY

In [141]:
df.mean(numeric_only=True)

value1    167.0
value2    210.5
dtype: float64

Sort Values In Pandas

In [142]:
df.sort_values(by='value2',ascending=True)

   value1  value2 value3
1   167.0   121.0    VYU
2   234.0   210.5    NMA
3   167.0   210.5    IUY
0   100.0   300.0    XUI

In [144]:
data.sort_values(by='price', ascending=False).head(20)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
44,1,?,isuzu,gas,std,two,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,?
45,0,?,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,?
129,1,?,porsche,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288,5750,17,28,?
9,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.4,7.0,160,5500,16,22,?
188,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.4,10.0,100,5500,26,32,9995
169,2,134,toyota,gas,std,two,hatchback,rwd,front,98.4,...,146,mpfi,3.62,3.5,9.3,116,4800,24,30,9989
175,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,122,mpfi,3.31,3.54,8.7,92,4200,27,32,9988
190,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,109,mpfi,3.19,3.4,8.5,90,5500,24,29,9980
143,0,102,subaru,gas,std,four,sedan,fwd,front,97.2,...,108,mpfi,3.62,2.64,9.0,94,5200,26,32,9960
80,3,153,mitsubishi,gas,turbo,two,hatchback,fwd,front,96.3,...,110,spdi,3.17,3.46,7.5,116,5500,23,30,9959
131,2,?,renault,gas,std,two,hatchback,fwd,front,96.1,...,132,mpfi,3.46,3.9,8.7,?,?,23,31,9895
168,2,134,toyota,gas,std,two,hardtop,rwd,front,98.4,...,146,mpfi,3.62,3.5,9.3,116,4800,24,30,9639
100,0,106,nissan,gas,std,four,sedan,fwd,front,97.2,...,120,2bbl,3.33,3.47,8.5,97,5200,27,34,9549
166,1,168,toyota,gas,std,two,hatchback,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.4,112,6600,26,29,9538
187,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.4,23.0,68,4500,37,42,9495
165,1,168,toyota,gas,std,two,sedan,rwd,front,94.5,...,98,mpfi,3.24,3.08,9.4,112,6600,26,29,9298
130,0,?,renault,gas,std,four,wagon,fwd,front,96.1,...,132,mpfi,3.46,3.9,8.7,?,?,23,31,9295
87,1,125,mitsubishi,gas,turbo,four,sedan,fwd,front,96.3,...,110,spdi,3.17,3.46,7.5,116,5500,23,30,9279
88,-1,137,mitsubishi,gas,std,four,sedan,fwd,front,96.3,...,110,spdi,3.17,3.46,7.5,116,5500,23,30,9279
162,0,91,toyota,gas,std,four,sedan,fwd,front,95.7,...,98,2bbl,3.19,3.03,9.0,70,4800,28,34,9258

GroupBY

In [146]:
data.groupby('fuel-type').count()

,symboling,normalized-losses,make,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
fuel-type,,,,,,,,,,,,,,,,,,,,,
diesel,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
gas,185,185,185,185,185,185,185,185,185,185,...,185,185,185,185,185,185,185,185,185,185

Count() & Value_Count()

In [147]:
data['make'].count()

np.int64(205)

In [148]:
data['make'].value_counts()

make
toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
subaru           12
volkswagen       12
volvo            11
peugot           11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
alfa-romero       3
chevrolet         3
jaguar            3
renault           2
mercury           1
Name: count, dtype: int64

Concatenate Function

In [149]:
mm={'one':[4,5,6,3,1],
    'two':[1,3,4,5,7],
    'letter':['a','a','b','b','c']}

In [150]:
mm

{'one': [4, 5, 6, 3, 1],
 'two': [1, 3, 4, 5, 7],
 'letter': ['a', 'a', 'b', 'b', 'c']}

In [151]:
mm=pd.DataFrame(mm)

In [152]:
mm

   one  two letter
0    4    1      a
1    5    3      a
2    6    4      b
3    3    5      b
4    1    7      c

In [153]:
newdf=pd.concat([df,mm])

In [154]:
newdf

   value1  value2 value3  one  two letter
0   100.0   300.0    XUI  NaN  NaN    NaN
1   167.0   121.0    VYU  NaN  NaN    NaN
2   234.0   210.5    NMA  NaN  NaN    NaN
3   167.0   210.5    IUY  NaN  NaN    NaN
0     NaN     NaN    NaN  4.0  1.0      a
1     NaN     NaN    NaN  5.0  3.0      a
2     NaN     NaN    NaN  6.0  4.0      b
3     NaN     NaN    NaN  3.0  5.0      b
4     NaN     NaN    NaN  1.0  7.0      c

In [155]:
newdf=pd.concat([df,mm],axis=1)

In [156]:
newdf

   value1  value2 value3  one  two letter
0   100.0   300.0    XUI    4    1      a
1   167.0   121.0    VYU    5    3      a
2   234.0   210.5    NMA    6    4      b
3   167.0   210.5    IUY    3    5      b
4     NaN     NaN    NaN    1    7      c

Join & Merge

In [157]:
friends={'abubakar':10000,
         'ahamd':5000,
         'basil':440,
         'mughal':6700,
         'taha':300}
area={'abubakar':'hassanabdal',
         'ahamd':'overseas',
         'arayash':np.nan,
         'basil':'bahria',
         'ar':np.nan,
         'mughal':'chor',
         'taha':'wah'}

In [159]:
frienddf=pd.DataFrame.from_dict(friends, orient='index',columns=['friend'])
areadf=pd.DataFrame.from_dict(area, orient='index',columns=['area'])

In [160]:
frienddf

          friend
abubakar   10000
ahamd       5000
basil        440
mughal      6700
taha         300

In [161]:
areadf

                 area
abubakar  hassanabdal
ahamd        overseas
arayash           NaN
basil          bahria
ar                NaN
mughal           chor
taha              wah

In [162]:
joined_df=areadf.join(frienddf, how='left')

In [163]:
joined_df

                 area   friend
abubakar  hassanabdal  10000.0
ahamd        overseas   5000.0
arayash           NaN      NaN
basil          bahria    440.0
ar                NaN      NaN
mughal           chor   6700.0
taha              wah    300.0

In [164]:
joined_df=areadf.join(frienddf, how='right')

In [165]:
joined_df

                 area  friend
abubakar  hassanabdal   10000
ahamd        overseas    5000
basil          bahria     440
mughal           chor    6700
taha              wah     300

In [166]:
joined_df=areadf.join(frienddf, how='inner')

In [167]:
joined_df

                 area  friend
abubakar  hassanabdal   10000
ahamd        overseas    5000
basil          bahria     440
mughal           chor    6700
taha              wah     300

In [168]:
joined_df=areadf.join(frienddf, how='outer')

In [169]:
joined_df

                 area   friend
abubakar  hassanabdal  10000.0
ahamd        overseas   5000.0
ar                NaN      NaN
arayash           NaN      NaN
basil          bahria    440.0
mughal           chor   6700.0
taha              wah    300.0

Merge

In [170]:
frienddf.index.name='names'
areadf.index.name='names'

In [171]:
print(areadf)
print('-'*10)
print(frienddf)

                 area
names
abubakar  hassanabdal
ahamd        overseas
arayash           NaN
basil          bahria
ar                NaN
mughal           chor
taha              wah
----------
          friend
names
abubakar   10000
ahamd       5000
basil        440
mughal      6700
taha         300

In [173]:
pd.merge(areadf,frienddf,on='names')

                 area  friend
names
abubakar  hassanabdal   10000
ahamd        overseas    5000
basil          bahria     440
mughal           chor    6700
taha              wah     300

In [174]:
pd.merge(areadf,frienddf,on='names',how='left')

                 area   friend
names
abubakar  hassanabdal  10000.0
ahamd        overseas   5000.0
arayash           NaN      NaN
basil          bahria    440.0
ar                NaN      NaN
mughal           chor   6700.0
taha              wah    300.0